const quotes: string[] = [
  "The body achieves what the mind believes.",
  "One walk at a time. One meal at a time. One day at a time.",
  "Discipline is choosing between what you want now and what you want most.",
  "Small daily improvements are the key to staggering long-term results.",
  "Your future self is watching you right now through memories.",
  "Don't count the days. Make the days count.",
  "The pain you feel today will be the strength you feel tomorrow.",
  "Success is the sum of small efforts repeated day in and day out.",
  "You don't have to be extreme, just consistent.",
  "Wake up with determination. Go to bed with satisfaction.",
  "The only bad workout is the one that didn't happen.",
  "Progress, not perfection.",
  "Every step forward is a step away from where you used to be.",
  "Your body hears everything your mind says. Stay positive.",
  "It's not about having time. It's about making time.",
  "Hardest part is starting. The rest is momentum.",
  "You are one decision away from a totally different life.",
  "What you do every day matters more than what you do once in a while.",
  "Be stronger than your strongest excuse.",
  "Health is not about the weight you lose but the life you gain.",
  "Fall in love with taking care of yourself.",
  "The secret of getting ahead is getting started.",
  "Strive for progress, not perfection.",
  "Your only limit is your mind.",
  "Push yourself because no one else is going to do it for you.",
  "Great things never come from comfort zones.",
  "It always seems impossible until it's done.",
  "Don't stop when you're tired. Stop when you're done.",
  "Believe you can and you're halfway there.",
  "A year from now, you'll wish you had started today.",
  "The distance between who you are and who you want to be is discipline.",
  "You are stronger than you think.",
  "Make yourself a priority. At the end of the day, you're your longest commitment.",
  "Motivation gets you started. Habit keeps you going.",
  "Your health is an investment, not an expense.",
  "Transformation is not a future event. It is a present activity.",
  "Stop wishing. Start doing.",
  "Results happen over time, not overnight. Work hard, stay consistent, and be patient.",
  "Take care of your body. It's the only place you have to live.",
  "Every morning you have two choices: continue to sleep with your dreams, or wake up and chase them.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "Nothing will work unless you do.",
  "Don't wish for it. Work for it.",
  "You did not wake up today to be mediocre.",
  "Sore today, strong tomorrow.",
  "When you feel like quitting, remember why you started.",
  "Success doesn't come from what you do occasionally. It comes from what you do consistently.",
  "Your body can stand almost anything. It's your mind that you have to convince.",
  "If it doesn't challenge you, it doesn't change you.",
  "You are what you repeatedly do. Excellence is not an act, but a habit.",
  "Winners are not people who never fail, but people who never quit.",
  "The harder the battle, the sweeter the victory.",
  "Strength does not come from physical capacity. It comes from an indomitable will.",
  "You're not going to master the rest of your life in one day. Just relax. Master the day.",
  "Do something today that your future self will thank you for.",
  "Every champion was once a contender who refused to give up.",
  "It's going to be hard, but hard does not mean impossible.",
  "The only way to do great work is to love what you do daily.",
  "Your life does not get better by chance. It gets better by change.",
  "Don't limit your challenges. Challenge your limits.",
  "Perseverance is not a long race. It is many short races, one after another.",
  "You don't need to see the whole staircase. Just take the first step.",
  "Be the energy you want to attract.",
  "The difference between ordinary and extraordinary is that little extra.",
  "Sweat is just fat crying.",
  "Set goals that make you want to jump out of bed in the morning.",
  "The struggle you're in today is developing the strength you need for tomorrow.",
  "Stay patient and trust your journey.",
  "Every day is a chance to get stronger, to eat better, to live healthier.",
  "Success is what comes after you stop making excuses.",
  "What seems impossible today will one day become your warm-up.",
  "A healthy outside starts from the inside.",
  "You are worth the investment of your own time and energy.",
  "The comeback is always stronger than the setback.",
  "Work until your idols become your rivals.",
  "Don't stop until you're proud.",
  "Consistency is what transforms average into excellence.",
  "If you want something you've never had, you must do something you've never done.",
  "Life has no remote. Get up and change it yourself.",
  "Be somebody nobody thought you could be.",
  "On the days you want to quit, remember the days you prayed for what you have now.",
  "Doubt kills more dreams than failure ever will.",
  "You can feel sore tomorrow or you can feel sorry tomorrow. You choose.",
  "Dream it. Believe it. Build it.",
  "Today's actions are tomorrow's results.",
  "Champions keep playing until they get it right.",
  "You're not just building a body. You're building a life.",
  "Ninety days is all it takes to become someone you've never been.",
  "The last 10% is where the magic happens. Don't quit early.",
  "You started this journey for a reason. Remember that reason today.",
];

export default quotes;
